### ISSUE TITLE
URLpilgrim issue : The tool is testing for non-links 

### ISSUE THREAD

**Issue by zg3d** [PedroFonsecaDEV/URLpilgrim#1]
When I test the tool for this  https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List url/html file the tool is testing for non-links
![image](https://user-images.githubusercontent.com/25188774/93913355-fa3f3700-fcd2-11ea-90d5-556824b98c6f.png)

As you can see in the image
The tool is trying to test for Woosle and Wissmann which are not links.

This could be because the parser is going line by line instead of testing the complete document.

because in the link above there are urls that are on multiple lines.

Check out 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match
The match command creates an array of all matches in a string

**Comment by PedroFonsecaDEV** [comment]
Thanks, @zg3d! 

Everything should be working fine now.
