### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by Meneguini** [PedroFonsecaDEV/URLpilgrim#10]
Package-lock.json is on Github, and it is causing a bug when installing the program on wsl2.

**Comment by PedroFonsecaDEV** [comment]
Thanks @Meneguini 
You are right. Do you want to work on this issue?

**Comment by Meneguini** [comment]
@PedroFonsecaDEV 
Yes, I would like to work on this issue.
Thank you

**Comment by PedroFonsecaDEV** [comment]
Sure. Thank you.
