### ISSUE TITLE
Add ignore feature that ignore all urls in a specified file

### ISSUE THREAD

**Issue by phast184** [PedroFonsecaDEV/URLpilgrim#6]
Hi I would like to work on this issue.

**Comment by PedroFonsecaDEV** [comment]
Please let me know if you need anything.

**Comment by phast184** [comment]
![image](https://user-images.githubusercontent.com/29710922/96362291-743dd100-1156-11eb-9f23-20f36179ca0d.png)
![image](https://user-images.githubusercontent.com/29710922/96362294-7869ee80-1156-11eb-9b7f-847cd7d0c029.png)
![image](https://user-images.githubusercontent.com/29710922/96362296-7acc4880-1156-11eb-8ade-934c5ea9a7ff.png)
The 1st pic is "icheck.txt" in which there are the urls that need to be ignored
The 2nd pic is "testURL.txt" in which there are the URLs which will be ignored if they start with any URLs declared in "icheck.txt"
The third pic is the output of the text

**Comment by phast184** [comment]
Btw, the forked repo is: https://github.com/phast184/URLpilgrim and the branch name is issue-6

**Comment by PedroFonsecaDEV** [comment]
Thanks.
See you soon.
